The idna subdirectory is now buildable, testable, and stage-installable.
Also, all the pieces we were using have been updated to the code from
libidn 1.4, and the relevant parts of the library's own test suite
have been imported from libidn 0.6.14.  [I did this apparently
deranged thing to avoid GPLv3, which license applies to the test suite
in libidn 1.4 -- 0.6.14 is the last released version where the test
suite is GPLv2.  The library itself remains LGPL 2.1 in version 1.4.
It happens that the test suite in 0.6.14 is identical to that in 1.4
except for licensing.]

 * idna/tst_idna.c, idna/tst_idna2.c, idna/tst_nfkc.c,
 * idna/tst_punycode.c idna/tst_stringprep.c, idna/utils.c,
 * idna/utils.h: New files taken from libidn-0.6.14.

 * idna/gunicomp.h, idna/gunidecomp.h, idna/idna.c, idna/idna.h
 * idna/nfkc.c, idna/profiles.c, idna/punycode.c, idna/punycode.h
 * idna/rfc3454.c, idna/stringprep.c, idna/toutf8.c, idna/version.c:
   Update to libidn-1.4.
 * idna/c-ctype.c, idna/c-ctype.h, idna/c-strcase.h
 * idna/c-strcasecmp.c, idna/striconv.c, idna/striconv.h
 * idna/strverscmp.c, idna/strverscmp.h: New files taken from libidn-1.4.

 * idna/idn-int.h: Dropped; is now generated at build time.
 * idna/stringprep.h: Rename to idna/stringprep.h.in and update to
   libidn-1.4.

 * idna/Makefile.am: Rewrite based loosely on lib/Makefile.am and
   tests/Makefile.am in libidn-1.4.
 * idna/configure.ac: Similarly.

 * monotone/po: Move back to the top level.
 * configure.ac: Invoke AM_GNU_GETTEXT here, thank you autopoint.
 * Makefile.am: Pass a subset of top-level configure arguments to
   library configure scripts.
 * .mtn-ignore: Update.

diff --git a/idna/Makefile.am b/idna/Makefile.am
--- a/idna/Makefile.am
+++ b/idna/Makefile.am
@@ -1,6 +1,87 @@
-lib_LIBRARIES = libidna.a
-include_HEADERS = idna.h punycode.h stringprep.h
-libidna_a_SOURCES =							\
-	gunibreak.h gunicomp.h gunidecomp.h idna.c idn-int.h nfkc.c	\
-	profiles.c punycode.c rfc3454.c stringprep.c toutf8.c		\
-	version.c
+## Process this file with automake to produce Makefile.in
+# Copyright (C) 2002, 2003, 2004, 2005, 2006, 2007 Simon Josefsson.
+# Copyright (C) 2004 Free Software Foundation, Inc.
+#
+# This file is part of GNU Libidn.
+#
+# GNU Libidn is free software; you can redistribute it and/or modify
+# it under the terms of the GNU Lesser General Public License as
+# published by the Free Software Foundation; either version 2.1 of
+# the License, or (at your option) any later version.
+#
+# GNU Libidn is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Lesser General Public License for more details.
+#
+# You should have received a copy of the GNU Lesser General Public
+# License along with GNU Libidn; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
+
+# MONOTONE: A bunch of undesirable stuff has been pruned from this
+# MONOTONE: Makefile.  Also, the required pieces of gnulib have been
+# MONOTONE: incorporated into this makefile rather than having a gl
+# MONOTONE: subdirectory, and the method for creating idn-int.h is
+# MONOTONE: very different.
+
+DEFS = -DLIBIDN_BUILDING @DEFS@
+
+lib_LIBRARIES = libidn.a
+idn_int = idn-int.h
+
+BUILT_SOURCES = $(idn_int)
+DISTCLEANFILES = $(idn_int)
+include_HEADERS = stringprep.h idna.h punycode.h
+nodist_include_HEADERS = $(idn_int)
+
+idn-int.h: config.h
+	inttypes_h=$$(grep -q '^#define HAVE_INTTYPES_H' config.h; echo $$?);\
+	stdint_h=$$(grep -q '^#define HAVE_STDINT_H' config.h; echo $$?);\
+	uint32_t=$$(grep -q '^#define uint32_t' config.h; echo $$?);\
+	uint16_t=$$(grep -q '^#define uint16_t' config.h; echo $$?);\
+	if [ $$uint32_t -ne 0 ] || [ $$uint16_t -ne 0 ];\
+	then if [ $$stdint_h -eq 0 ];\
+	     then echo '#include <stdint.h>' > idn-int.h.T;\
+	     elif [ $$inttypes_h -eq 0 ];\
+	     then echo '#include <inttypes.h>' > idn-int.h.T;\
+	     else echo 'Missing inttypes.h and stdint.h' >&2; exit 1;\
+	     fi;\
+	fi;\
+	if [ $$uint32_t -eq 0 ] || [ $$uint16_t -eq 0 ];\
+	then grep '^#define uint[0-9]*_t' config.h >> idn-int.h.T;\
+	fi;\
+	mv -f idn-int.h.T idn-int.h
+
+libidn_a_SOURCES = gunibreak.h gunicomp.h gunidecomp.h \
+	nfkc.c toutf8.c version.c \
+	stringprep.h.in stringprep.c rfc3454.c profiles.c \
+	punycode.h punycode.c \
+	idna.h idna.c \
+	striconv.h striconv.c strverscmp.h strverscmp.c \
+	c-strcase.h c-strcasecmp.c c-ctype.c c-ctype.h
+
+# This is a subset of the tests originally in a separate directory
+# of the libidn distribution.  tst_pr29, tst_strerror, and tst_tld
+# have been excluded, since the corresponding code has been excluded
+# from the library proper.
+
+TESTS = tst_stringprep$(EXEEXT) tst_punycode$(EXEEXT)		\
+	tst_idna$(EXEEXT) tst_idna2$(EXEEXT) tst_nfkc$(EXEEXT)
+check_PROGRAMS = $(TESTS)
+
+# You might think there was a more elegant way to do this, but no.
+tst_stringprep_SOURCES = tst_stringprep.c utils.c utils.h
+tst_punycode_SOURCES   = tst_punycode.c utils.c utils.h
+tst_idna_SOURCES       = tst_idna.c utils.c utils.h
+tst_idna2_SOURCES      = tst_idna2.c utils.c utils.h
+tst_nfkc_SOURCES       = tst_nfkc.c utils.c utils.h
+
+tst_stringprep_LDADD   = libidn.a
+tst_punycode_LDADD     = libidn.a
+tst_idna_LDADD         = libidn.a
+tst_idna2_LDADD        = libidn.a
+tst_nfkc_LDADD         = libidn.a
+
+# This is necessary because autoreconf doesn't pay attention to
+# AC_CONFIG_MACRO_DIR.
+ACLOCAL_AMFLAGS = -I ../m4
